AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.5
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Max: 20
  Exclude:
    - spec/**/*
